import SupabaseProvider from "@/context/SupabaseContext";
import "./globals.css";
import { headers, cookies } from "next/headers";
import { Inter } from "next/font/google";
import { createServerComponentSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { PokemonProvider } from "@/context/PokemonContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentSupabaseClient({
    headers,
    cookies,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <PokemonProvider>
      <SupabaseProvider session={session}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SupabaseProvider>
    </PokemonProvider>
  );
}
